In [4]:
import gym
import numpy as np
from LearningAlgorithms.q_learner import Q_Learner

In [16]:
class My_Q_Learner(Q_Learner):
    def features(self, state, action):
        action_sign = 2*action - 1
        feat1 = np.abs([state[2] + action_sign])
        return np.concatenate((state, feat1))
    
    def environment(self):
        return gym.make('CartPole-v0')

In [17]:
env = gym.make('CartPole-v0')

actions_arr = np.arange(env.action_space.n)
d = 5
learning_rate = 0.01
epsilon = 0.9
discount_factor = 0.95

agent = My_Q_Learner(actions_arr, d, learning_rate, 
                     epsilon, discount_factor)

num_episodes = 500
for i in range(num_episodes):
    state = env.reset()
    done = False
    rounds = 0
    while not done:
        action = agent.best_action(state, training=True)
        old_state = state
        state, reward, done, info = env.step(action)
        agent.update_parameters(old_state, state, action, reward)
        rounds += 1
    if i % 100 == 0:
        print("\n--> Game Over. Rounds: {}".format(rounds))
        print("Parameter vector:\n{}".format(agent.theta))
print("\n--> Game Over. Rounds: {}".format(rounds))
print("Parameter vector:\n{}".format(agent.theta))


--> Game Over. Rounds: 8 | Score: 8.0
Parameter vector:
[ 0.70328656  0.46409958 -0.00767335 -0.2577557  -0.47276073]

--> Game Over. Rounds: 25 | Score: 25.0
Parameter vector:
[-0.04097099 -0.05413197  0.07501933  0.12186901  0.98737589]

--> Game Over. Rounds: 38 | Score: 38.0
Parameter vector:
[-0.05292808 -0.05943205  0.08768303  0.10019524  0.98789628]

--> Game Over. Rounds: 42 | Score: 42.0
Parameter vector:
[-0.08626871 -0.00987788  0.0888658   0.00929289  0.99220797]

--> Game Over. Rounds: 24 | Score: 24.0
Parameter vector:
[-0.06052526  0.01004273  0.07872077  0.04277701  0.99408702]

--> Game Over. Rounds: 51 | Score: 51.0
Parameter vector:
[-0.06998458 -0.05788397  0.08698238  0.15210352  0.98033167]


In [25]:
import time
state = env.reset()
done = False
rounds = 0
while not done:
    env.render()
    time.sleep(0.1)
    action = agent.best_action(state, training=False)
    state, reward, done, info = env.step(action)
    rounds += 1
    #print(state, action)
print("\n--> Game Over. Rounds: {}".format(rounds))
env.close()


--> Game Over. Rounds: 40
