### Testing Q_Learner class on CartPole
We test if the Q_Learner class performs significantly better than an agent which plays without caring of the environment state.

Spoiler: it does. By setting by hand two features, the agent learn how to exploit the information they carry.

CartPole info:


https://gym.openai.com/envs/CartPole-v0/


https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

In [3]:
import gym
import numpy as np
from Modules import Q_Learner

In [4]:
# Overload the abstract method features()
class My_Q_Learner(Q_Learner):
    def features(self, state, action):
        feat1 = state[2:3]
        action_sign = 2*action - 1
        feat2 = np.abs([state[2] + action_sign])
        bias = np.ones(1)
        return np.concatenate((feat1, feat2, bias))

In [5]:
# Generate the environment
env = gym.make('CartPole-v0')

# Parameters
actions_arr = np.arange(env.action_space.n)
d = 3 # <--- set the right number of features
learning_rate = 0.01
epsilon = 0.9
discount_factor = 0.95

# Initialize the agent
agent = My_Q_Learner(actions_arr, d, learning_rate, 
                     epsilon, discount_factor)

# Train the agent on a number of matches (num_episodes)
# For each episode count the number of rounds the agent survived
num_episodes = 500
for i in range(num_episodes):
    state = env.reset()
    done = False
    rounds = 0
    while not done:
        action = agent.best_action(state, training=True)
        old_state = state
        state, reward, done, info = env.step(action)
        agent.update_parameters(old_state, state, action, reward)
        rounds += 1
    if i % 100 == 0:
        print("\n--> Game Over. Rounds: {}".format(rounds))
        print("Parameter vector:\n{}".format(agent.theta))
print("\n--> Game Over. Rounds: {}".format(rounds))
print("Parameter vector:\n{}".format(agent.theta))

/home/fra/Softwares/anaconda3/envs/pytorch/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)



--> Game Over. Rounds: 54
Parameter vector:
[-0.76997     0.57574827  0.27506385]

--> Game Over. Rounds: 24
Parameter vector:
[0.32158083 0.68152317 0.65735222]

--> Game Over. Rounds: 54
Parameter vector:
[0.29633594 0.689978   0.66039032]

--> Game Over. Rounds: 54
Parameter vector:
[0.27122152 0.69303202 0.66794125]

--> Game Over. Rounds: 39
Parameter vector:
[0.29829979 0.68789529 0.66167764]

--> Game Over. Rounds: 34
Parameter vector:
[0.30291693 0.68789696 0.65957495]


In [7]:
# Watch the trained agent playing
import time
state = env.reset()
done = False
rounds = 0
while not done:
    env.render()
    time.sleep(0.1)
    action = agent.best_action(state, training=False)
    state, reward, done, info = env.step(action)
    rounds += 1
    #print(state, action)
print("\n--> Game Over. Rounds: {}".format(rounds))
env.close()


--> Game Over. Rounds: 48
